Divide by Zero Exception fixed
trishnaguha/Calci pull request #5
Opened 2016-11-08 05:03 UTC by SRvSaha

2016-11-08 12:28 UTC, trishnaguha requested changes

2016-11-08 12:28 UTC, trishnaguha commented on main.py
> +    val = a + b
Can you move the docstring inside method?

2016-11-08 12:34 UTC, trishnaguha requested changes

2016-11-08 12:34 UTC, trishnaguha commented on main.py
> +                                     epilog="Enter two numbers for addition,subtraction and so on....\n Enter only one number for percentage calculation,factorial and so on....")
It would be nice if we can follow PEP8 rule. Could you break the text in couple of lines?

2016-11-08 12:34 UTC, SRvSaha commented on main.py
> +    val = a + b
Well, I can do that. Will be updating the asked changes in some time.

2016-11-08 12:35 UTC, trishnaguha commented
Otherwise Looks good to me.

2016-11-08 12:36 UTC, SRvSaha commented on main.py
> +                                     epilog="Enter two numbers for addition,subtraction and so on....\n Enter only one number for percentage calculation,factorial and so on....")
Actually, I did Auto PEP8 formatting using Anaconda plugin in Sublime Text. 

Anyways, I will do the changes. :) Thanks for giving me an opportunity

2016-11-08 14:33 UTC, SRvSaha commented
![image](https://cloud.githubusercontent.com/assets/13312352/20102979/15e6d4e4-a5ee-11e6-860b-bda01c02b71b.png)

I think there's something wrong going on behind the scene.
As per the code there should have been a new line after so on... And the Enter only one num bla bla should come in new line. But why is this "\n" not working ? Should I keep it the way it is any fix the issue of "line too long " according to PEP8 or should I work on the "\n" thing as well??
![image](https://cloud.githubusercontent.com/assets/13312352/20102999/33a1d876-a5ee-11e6-90ff-98de0832a678.png)
"

2016-11-08 15:17 UTC, SRvSaha commented
Glad to fix all the issues pointed out by you and the ones I found need to be fixed.

Fixed Issues :
1. PEP8 Guideline based DOCSTRING ERROR and LINE TOO LONG ERROR.
2. Added formatter class for epilog in argument parser for better readability & fixed the newline issue.
3. The percentage method is modified a bit so that the division is more generic.

Hoping for a merge for my first contribution to Open Source :)

2016-11-09 04:37 UTC, SRvSaha commented
Changed made :

1. Added feature of log2(x) which is very important since most of the times we deal with log2(x) in Computer Science.
2. Updated Readme file with the logarithm2(x)
3. Fixed all PEP8 errors (except docstring missing in test_main.py) in the codebase.

2016-11-15 08:48 UTC, trishnaguha commented
Thanks @SRvSaha .

2016-11-15 08:48 UTC, merged